apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.component_id}}
  description: {{cookiecutter.description}}
  annotations:
    github.com/project-slug: {{cookiecutter.destination.git.owner + "/" + cookiecutter.destination.git.name}}
    backstage.io/techdocs-ref: url:{{cookiecutter.storePath}}
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner}}
