config:
  host: {{cookiecutter.component_id}}
  namespace: {{cookiecutter.component_id}}-service-dev
  image:
    name: uswest2fpmt.jfrog.io/{{cookiecutter.component_id}}-docker-dev-local/{{cookiecutter.component_id}}
    tag: v0.0.1
