apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{cookiecutter.component_id}}
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
  name: {{cookiecutter.component_id}}
  namespace: '{{"{{ .Values.config.namespace }}"}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.component_id}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{cookiecutter.component_id}}
    spec:
      containers:
      - image: uswest2fpmt.jfrog.io/default-docker-virtual/vad1mo/hello-world-rest
        imagePullPolicy: IfNotPresent
        name: {{cookiecutter.component_id}}
        resources: {}
        ports:
          - containerPort: 5050 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 5050
          periodSeconds: 5
    imagePullSecrets:
      - name: artifact-registry
status: {}
