apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{cookiecutter.component_id}}
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
  name: {{cookiecutter.component_id}}
  namespace: {{ .Values.config.namespace }}
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{cookiecutter.component_id}}
